repo_name: 'Corratech'
repo_url: https://github.com/corratech/oss-wiki
site_name: Corratech OSS
site_url: https://github.com/corratech/oss-wiki/
site_description: Corrattech OSS Wiki
site_author: Corra Devops
edit_uri: edit/main/docs/docs/

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - toc.integrate
    #- header.autohide
  palette:
    scheme: default
  font:
    text: Roboto
    code: Roboto Mono
  favicon: images/favicon.png
  icon:
    logo: fontawesome/solid/robot
    repo: fontawesome/brands/github

copyright: 'Copyright &copy; 2020-2021 Corratech'


markdown_extensions:
  - mdx_math:
      enable_dollar_delimiter: true
  - fontawesome_markdown
  - admonition
  - footnotes
  - attr_list
  - codehilite
  - toc:
      permalink: ⚓︎
      toc_depth: 3
nav:
  - 'index.md'
  - 'psy-mcloud.md'
