name: deploy-wiki
on:
  schedule:
    - cron: 0 0 * * *
  push: 
    branches: 
      - main
  workflow_dispatch:
  pull_request: 

jobs: 
  document: 
    name: build document 
    runs-on: ubuntu-20.04 
    steps:
      - uses: actions/checkout@v2-beta 
      - name: Set up Python 
        uses: actions/setup-python@v1
        with:
          python-version: {{ secrets.PYTHON_VERSION }}
      - name: Install
        run: pip3 install mkdocs mkdocs-material fontawesome_markdown mdx_unimoji mkdocs-mermaid2-plugin pymdown-extensions plantuml-markdown python-markdown-math 
        
      - name: Generate documentation
        run: mkdocs build 
        working-directory: docs
        
      - uses: actions/upload-artifact@v2 
        if: ${{ github.event_name == 'pull_request'}} 
        with:
          name: site 
          path: docs/site 
          
      - uses: peaceiris/actions-gh-pages@v3 
        if: ${{ github.event_name != 'pull_request'}} 
        with:
          github_token: ${{ secrets.OSSWIKI_TOKEN }} 
          publish_dir: docs/site
